### PR TITLE
Create Multipass.ts

### PR DESCRIPTION
**Pull request by ormaq**

### CODE REVIEW

**Comment by ormaq** [comment]
Simple commit

**Comment by ZuShi0** [comment]
Looks like this may be a stale PR? If so, make sure to close it

**Comment by Harshal609** [comment]
Lets get this done!

**Comment by jtyrmn** [comment]
Is this a stale PR?

**Comment by ZuShi0** [comment]
I think so. I'll close this down since it seems like it won't be used

**Pull request closed without merging**
